select * from CUSTOMER;

select * from ADDRESS;

select *
from DEPARTMENTS;

select FIRST_NAME, LAST_NAME, ADDRESS, PHONE
from CUSTOMER join ADDRESS
on CUSTOMER.ADDRESS_ID = ADDRESS.ADDRESS_ID;

select FIRST_NAME, LAST_NAME, C.ADDRESS_ID, ADDRESS, PHONE
from CUSTOMER C LEFT JOIN ADDRESS A
                   on C.ADDRESS_ID = A.ADDRESS_ID;

Select FIRST_NAME, LAST_NAME,DEPARTMENT_NAME
from EMPLOYEES e join DEPARTMENTS d
on e.DEPARTMENT_ID = d.DEPARTMENT_ID;
